name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run coverage -- --no-cache --runInBand
      - name: Report coverage
        uses: codecov/codecov-action@v1.0.12
      - name: Build docs
        run: npm --prefix website run build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.node-version == '14.x'
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          allow_empty_commit: true
          cname: uniforms.tools
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.node-version == '14.x'
